# Generated by Django 5.2 on 2025-10-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='showroom/', verbose_name='Görsel')),
                ('section', models.CharField(choices=[('hero', 'Ana Sayfa Görseli'), ('living_room', 'Oturma Odası'), ('dining_room', 'Yemek Odası'), ('bedroom', 'Yatak Odası')], max_length=20, verbose_name='Bölüm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showroom Görseli',
                'verbose_name_plural': 'Showroom Görselleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
