# Generated by Django 5.2 on 2025-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showroomimage',
            options={'ordering': ['section', 'order', '-created_at'], 'verbose_name': 'Showroom Görseli', 'verbose_name_plural': 'Showroom Görselleri'},
        ),
        migrations.AddField(
            model_name='showroomimage',
            name='button_text',
            field=models.CharField(default='Detaylar', max_length=50, verbose_name='Buton Metni'),
        ),
        migrations.AddField(
            model_name='showroomimage',
            name='button_url',
            field=models.CharField(default='#', max_length=200, verbose_name='Buton Linki'),
        ),
        migrations.AddField(
            model_name='showroomimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='showroomimage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='showroomimage',
            name='section',
            field=models.CharField(choices=[('hero', 'Ana Sayfa Slider'), ('living_room', 'Oturma Odası'), ('dining_room', 'Yemek Odası'), ('bedroom', 'Yatak Odası')], max_length=20, verbose_name='Bölüm'),
        ),
    ]
