# Generated by Django 5.2 on 2025-10-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_showroomimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroomimage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='showroomimage',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='showroomimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='showroomimage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='showroomimage',
            name='title',
        ),
    ]
